add wattermark in UI
arshadkazmi42/gh-rhof pull request #50
Opened 2022-10-06 20:12 UTC by jayeshchoudhary

<img width="901" alt="image" src="https://user-images.githubusercontent.com/41536903/194409277-6ca50d61-b797-469a-b8fb-7dc3b785f381.png">

2022-10-06 20:12 UTC, jayeshchoudhary commented
@arshadkazmi42 can you please review

2022-10-06 20:17 UTC, jayeshchoudhary commented
closes #23

2022-10-06 21:45 UTC, arshadkazmi42 requested changes
Thank you for working on this.

We want the watermark to be part of the `Markdown` section, so when someone uses the generated markdown, it will also show the watermark

2022-10-06 21:45 UTC, arshadkazmi42 commented on src/components/HallOfFame.js
> +        <Typography color="textSecondary" className={classes.watermark}>
We want this to be part of the makrdown content. I think you can contact this using HTML into `hof` which is already getting passed to this component. We want the watermark to show up where ever the markdown is used.

2022-10-07 08:27 UTC, jayeshchoudhary commented
@arshadkazmi42 updated.

2022-10-07 08:47 UTC, arshadkazmi42 approved these changes
LGTM 🎉

2022-10-07 08:47 UTC, merged